from tkinter import *
tk = Tk()
l1 = Label(tk,text='Username')
l2 = Label(tk,text='Mob no')
l3 = Label(tk,text='email')
l4 = Label(tk,text='age')
l5 = Label(tk,text='password')
l6 = Label(tk,text='confrim password')
btn1 = Button(tk,text='Login')
btn2 = Button(tk,text='Cancel')
entry1_username = Entry(tk)
entry2_phone = Entry(tk)
entry3_email = Entry(tk)
entry4_age = Entry(tk)
entry5_password = Entry(tk)
entry6_password = Entry(tk)
l1.grid(row=0,column=0)
l2.grid(row=1,column=0)
l3.grid(row=2,column=0)
l4.grid(row=3,column=0)
l5.grid(row=4,column=0)
l6.grid(row=5,column=0)
entry1_username.grid(row=0,column=1)
entry2_phone.grid(row=1,column=1)
entry3_email.grid(row=2,column=1)
entry4_age.grid(row=3,column=1)
entry5_password.grid(row=4,column=1)
entry6_password.grid(row=5,column=1)
btn1.grid(row=6,column=0)
btn2.grid(row=6,column=1)
tk.mainloop()

