from tkinter import *
root = Tk()
l1 = Label(root,text='User name')
l2 = Label(root,text='Password')
l3 = Label(root,text='Repeat-Password')
entry1 = Entry(root)
entry2 = Entry(root)
entry3 = Entry(root)
l1.grid(row=0,column=0)
l2.grid(row=1,column=0)
l3.grid(row=2,column=0)
entry1.grid(row=0,column=1)
entry2.grid(row=1,column=1)
entry3.grid(row=2,column=1)
root.mainloop()
